name: Generate SBOM

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  generate-sbom:
    name: Generate Software Bill of Materials
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            if [ -f "package-lock.json" ]; then
              npm ci
            else
              npm install
            fi
          else
            echo "No package.json found, skipping npm install"
          fi

      - name: Generate SBOM with CycloneDX
        run: |
          npm install -g @cyclonedx/cyclonedx-npm
          if [ -f "package.json" ]; then
            cyclonedx-npm --output-file sbom.xml
          else
            echo "No package.json found, creating empty SBOM"
            echo '<?xml version="1.0" encoding="UTF-8"?><bom xmlns="http://cyclonedx.org/schema/bom/1.3" version="1"><metadata><component type="application"><name>Empty Project</name><version>0.0.0</version></component></metadata></bom>' > sbom.xml
          fi

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.xml
