name: License Compliance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  license-check:
    name: Check Dependency Licenses
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          if [ -f "package.json" ]; then
            if [ -f "package-lock.json" ]; then
              npm ci
            else
              npm install
            fi
          else
            echo "No package.json found, skipping npm install"
          fi

      - name: Install license-checker
        run: npm install -g license-checker

      - name: Check licenses
        run: |
          if [ -f "package.json" ]; then
            # Generate license report
            license-checker --json --out license-report.json
            
            # Check for disallowed licenses
            license-checker --failOn "GPL;AGPL;LGPL" || echo "Warning: Potentially problematic licenses found"
            
            # List all licenses for review
            echo "License summary:"
            license-checker --summary
          else
            echo "No package.json found, skipping license check"
            echo '{}' > license-report.json
          fi
